<a href="https://colab.research.google.com/github/sanikak1910/Machine_Learning/blob/main/ML(U)_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ML 1

Importing libraries


In [62]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Importing dataseet


In [63]:
df = pd.read_csv('/content/loan_data.csv')

In [64]:
df

person_age person_gender person_education  person_income  \
0            22.0        female           Master        71948.0   
1            21.0        female      High School        12282.0   
2            25.0        female      High School        12438.0   
3            23.0        female         Bachelor        79753.0   
4            24.0          male           Master        66135.0   
...           ...           ...              ...            ...   
44995        27.0          male        Associate        47971.0   
44996        37.0        female        Associate        65800.0   
44997        33.0          male        Associate        56942.0   
44998        29.0          male         Bachelor        33164.0   
44999        24.0          male      High School        51609.0   

       person_emp_exp person_home_ownership  loan_amnt        loan_intent  \
0                   0                  RENT    35000.0           PERSONAL   
1                   0                   OWN     1000.0          EDUCATION   
2                   3              MORTGAGE     5500.0            MEDICAL   
3                   0                  RENT    35000.0            MEDICAL   
4                   1                  RENT    35000.0            MEDICAL   
...               ...                   ...        ...                ...   
44995               6                  RENT    15000.0            MEDICAL   
44996              17                  RENT     9000.0    HOMEIMPROVEMENT   
44997               7                  RENT     2771.0  DEBTCONSOLIDATION   
44998               4                  RENT    12000.0          EDUCATION   
44999               1                  RENT     6665.0  DEBTCONSOLIDATION   

       loan_int_rate  loan_percent_income  cb_person_cred_hist_length  \
0              16.02                 0.49                         3.0   
1              11.14                 0.08                         2.0   
2              12.87                 0.44                         3.0   
3              15.23                 0.44                         2.0   
4              14.27                 0.53                         4.0   
...              ...                  ...                         ...   
44995          15.66                 0.31                         3.0   
44996          14.07                 0.14                        11.0   
44997          10.02                 0.05                        10.0   
44998          13.23                 0.36                         6.0   
44999          17.05                 0.13                         3.0   

       credit_score previous_loan_defaults_on_file  loan_status  
0               561                             No            1  
1               504                            Yes            0  
2               635                             No            1  
3               675                             No            1  
4               586                             No            1  
...             ...                            ...          ...  
44995           645                             No            1  
44996           621                             No            1  
44997           668                             No            1  
44998           604                             No            1  
44999           628                             No            1  

[45000 rows x 14 columns]

In [65]:
# iloc ':' specifies range
# iloc[row range,columns range]
X = df.iloc[:,:-1]
X

person_age person_gender person_education  person_income  \
0            22.0        female           Master        71948.0   
1            21.0        female      High School        12282.0   
2            25.0        female      High School        12438.0   
3            23.0        female         Bachelor        79753.0   
4            24.0          male           Master        66135.0   
...           ...           ...              ...            ...   
44995        27.0          male        Associate        47971.0   
44996        37.0        female        Associate        65800.0   
44997        33.0          male        Associate        56942.0   
44998        29.0          male         Bachelor        33164.0   
44999        24.0          male      High School        51609.0   

       person_emp_exp person_home_ownership  loan_amnt        loan_intent  \
0                   0                  RENT    35000.0           PERSONAL   
1                   0                   OWN     1000.0          EDUCATION   
2                   3              MORTGAGE     5500.0            MEDICAL   
3                   0                  RENT    35000.0            MEDICAL   
4                   1                  RENT    35000.0            MEDICAL   
...               ...                   ...        ...                ...   
44995               6                  RENT    15000.0            MEDICAL   
44996              17                  RENT     9000.0    HOMEIMPROVEMENT   
44997               7                  RENT     2771.0  DEBTCONSOLIDATION   
44998               4                  RENT    12000.0          EDUCATION   
44999               1                  RENT     6665.0  DEBTCONSOLIDATION   

       loan_int_rate  loan_percent_income  cb_person_cred_hist_length  \
0              16.02                 0.49                         3.0   
1              11.14                 0.08                         2.0   
2              12.87                 0.44                         3.0   
3              15.23                 0.44                         2.0   
4              14.27                 0.53                         4.0   
...              ...                  ...                         ...   
44995          15.66                 0.31                         3.0   
44996          14.07                 0.14                        11.0   
44997          10.02                 0.05                        10.0   
44998          13.23                 0.36                         6.0   
44999          17.05                 0.13                         3.0   

       credit_score previous_loan_defaults_on_file  
0               561                             No  
1               504                            Yes  
2               635                             No  
3               675                             No  
4               586                             No  
...             ...                            ...  
44995           645                             No  
44996           621                             No  
44997           668                             No  
44998           604                             No  
44999           628                             No  

[45000 rows x 13 columns]

In [90]:
categorical = df.select_dtypes(include=['object'])

In [94]:
categorical.columns


Index(['person_gender', 'person_education', 'person_home_ownership',
       'loan_intent', 'previous_loan_defaults_on_file'],
      dtype='object')

In [95]:
for col in categorical.columns:
  print(col,categorical[col].unique())

person_gender ['female' 'male']
person_education ['Master' 'High School' 'Bachelor' 'Associate' 'Doctorate']
person_home_ownership ['RENT' 'OWN' 'MORTGAGE' 'OTHER']
loan_intent ['PERSONAL' 'EDUCATION' 'MEDICAL' 'VENTURE' 'HOMEIMPROVEMENT'
 'DEBTCONSOLIDATION']
previous_loan_defaults_on_file ['No' 'Yes']


In [66]:
df.iloc[1:3,2:4]

person_education  person_income
1      High School        12282.0
2      High School        12438.0

In [67]:
# -1 specifies last index(column)
Y = df.iloc[:,-1]
Y

0        1
1        0
2        1
3        1
4        1
        ..
44995    1
44996    1
44997    1
44998    1
44999    1
Name: loan_status, Length: 45000, dtype: int64

In [68]:
df.describe()

person_age  person_income  person_emp_exp     loan_amnt  \
count  45000.000000   4.500000e+04    45000.000000  45000.000000   
mean      27.764178   8.031905e+04        5.410333   9583.157556   
std        6.045108   8.042250e+04        6.063532   6314.886691   
min       20.000000   8.000000e+03        0.000000    500.000000   
25%       24.000000   4.720400e+04        1.000000   5000.000000   
50%       26.000000   6.704800e+04        4.000000   8000.000000   
75%       30.000000   9.578925e+04        8.000000  12237.250000   
max      144.000000   7.200766e+06      125.000000  35000.000000   

       loan_int_rate  loan_percent_income  cb_person_cred_hist_length  \
count   45000.000000         45000.000000                45000.000000   
mean       11.006606             0.139725                    5.867489   
std         2.978808             0.087212                    3.879702   
min         5.420000             0.000000                    2.000000   
25%         8.590000             0.070000                    3.000000   
50%        11.010000             0.120000                    4.000000   
75%        12.990000             0.190000                    8.000000   
max        20.000000             0.660000                   30.000000   

       credit_score   loan_status  
count  45000.000000  45000.000000  
mean     632.608756      0.222222  
std       50.435865      0.415744  
min      390.000000      0.000000  
25%      601.000000      0.000000  
50%      640.000000      0.000000  
75%      670.000000      0.000000  
max      850.000000      1.000000

In [76]:
df.dtypes

person_age                        float64
person_gender                      object
person_education                   object
person_income                     float64
person_emp_exp                      int64
person_home_ownership              object
loan_amnt                         float64
loan_intent                        object
loan_int_rate                     float64
loan_percent_income               float64
cb_person_cred_hist_length        float64
credit_score                        int64
previous_loan_defaults_on_file     object
loan_status                         int64
dtype: object

In [69]:
df.isnull().sum()

person_age                        0
person_gender                     0
person_education                  0
person_income                     0
person_emp_exp                    0
person_home_ownership             0
loan_amnt                         0
loan_intent                       0
loan_int_rate                     0
loan_percent_income               0
cb_person_cred_hist_length        0
credit_score                      0
previous_loan_defaults_on_file    0
loan_status                       0
dtype: int64

In [83]:
df.shape

(45000, 14)

Encoding Categorical Values (Independent Variable)

In [70]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder


In [71]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),['person_gender','person_education','person_home_ownership','loan_intent','previous_loan_defaults_on_file'])], remainder='passthrough')

In [75]:
x = np.array(ct.fit_transform(X))
x

array([[1.00e+00, 0.00e+00, 0.00e+00, ..., 4.90e-01, 3.00e+00, 5.61e+02],
       [1.00e+00, 0.00e+00, 0.00e+00, ..., 8.00e-02, 2.00e+00, 5.04e+02],
       [1.00e+00, 0.00e+00, 0.00e+00, ..., 4.40e-01, 3.00e+00, 6.35e+02],
       ...,
       [0.00e+00, 1.00e+00, 1.00e+00, ..., 5.00e-02, 1.00e+01, 6.68e+02],
       [0.00e+00, 1.00e+00, 0.00e+00, ..., 3.60e-01, 6.00e+00, 6.04e+02],
       [0.00e+00, 1.00e+00, 0.00e+00, ..., 1.30e-01, 3.00e+00, 6.28e+02]])

In [74]:
pd.DataFrame(x)

0    1    2    3    4    5    6    7    8    9   ...   17   18    19  \
0      1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  1.0  0.0  22.0   
1      1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  ...  0.0  1.0  21.0   
2      1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  ...  1.0  0.0  25.0   
3      1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  23.0   
4      0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  1.0  0.0  24.0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   
44995  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  27.0   
44996  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  37.0   
44997  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  33.0   
44998  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  29.0   
44999  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  24.0   

            20    21       22     23    24    25     26  
0      71948.0   0.0  35000.0  16.02  0.49   3.0  561.0  
1      12282.0   0.0   1000.0  11.14  0.08   2.0  504.0  
2      12438.0   3.0   5500.0  12.87  0.44   3.0  635.0  
3      79753.0   0.0  35000.0  15.23  0.44   2.0  675.0  
4      66135.0   1.0  35000.0  14.27  0.53   4.0  586.0  
...        ...   ...      ...    ...   ...   ...    ...  
44995  47971.0   6.0  15000.0  15.66  0.31   3.0  645.0  
44996  65800.0  17.0   9000.0  14.07  0.14  11.0  621.0  
44997  56942.0   7.0   2771.0  10.02  0.05  10.0  668.0  
44998  33164.0   4.0  12000.0  13.23  0.36   6.0  604.0  
44999  51609.0   1.0   6665.0  17.05  0.13   3.0  628.0  

[45000 rows x 27 columns]

Encoding Categorical Variable(Dependent Variable) Output label

In [41]:
from sklearn.preprocessing import LabelEncoder

In [46]:
le =LabelEncoder()
y = le.fit_transform(Y)


In [43]:
y

array([1, 0, 1, ..., 1, 1, 1])

Splitting the dataset into the Training set and Test set

In [84]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [89]:
X_train
pd.DataFrame(X_train)

0    1    2    3    4    5    6    7    8    9   ...   17   18    19  \
0      0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  1.0  29.0   
1      1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  22.0   
2      1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  22.0   
3      0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  35.0   
4      1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  ...  1.0  0.0  25.0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   
35995  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  ...  1.0  0.0  40.0   
35996  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  28.0   
35997  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  29.0   
35998  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  27.0   
35999  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  1.0  23.0   

             20    21       22     23    24    25     26  
0       93802.0   7.0   1016.0   7.46  0.01   9.0  671.0  
1       77584.0   0.0  13000.0  14.11  0.17   3.0  612.0  
2       48618.0   0.0  10000.0  11.71  0.21   2.0  608.0  
3      157125.0  14.0   6600.0  17.93  0.04   5.0  594.0  
4       72385.0   2.0  18500.0  12.73  0.26   2.0  512.0  
...         ...   ...      ...    ...   ...   ...    ...  
35995   65596.0  13.0   5000.0   5.42  0.08  13.0  655.0  
35996   36633.0   5.0   5200.0   5.42  0.14   7.0  583.0  
35997   39466.0   6.0   6525.0  16.07  0.17   9.0  672.0  
35998   53580.0   4.0  13650.0  10.65  0.25   7.0  548.0  
35999   41843.0   0.0  10950.0   7.29  0.26   2.0  644.0  

[36000 rows x 27 columns]

In [86]:
X_test

array([[0.00e+00, 1.00e+00, 0.00e+00, ..., 3.30e-01, 4.00e+00, 6.14e+02],
       [1.00e+00, 0.00e+00, 0.00e+00, ..., 1.60e-01, 4.00e+00, 6.23e+02],
       [1.00e+00, 0.00e+00, 1.00e+00, ..., 6.00e-02, 7.00e+00, 6.63e+02],
       ...,
       [0.00e+00, 1.00e+00, 0.00e+00, ..., 1.00e-01, 4.00e+00, 6.86e+02],
       [1.00e+00, 0.00e+00, 0.00e+00, ..., 1.70e-01, 8.00e+00, 6.52e+02],
       [0.00e+00, 1.00e+00, 0.00e+00, ..., 1.90e-01, 6.00e+00, 6.70e+02]])

In [87]:
y_train


array([0, 0, 0, ..., 1, 1, 0])

In [88]:
y_test

array([1, 0, 0, ..., 0, 0, 0])

**Feature Scaling**

Feature Scaling should be done after train and test split to prevent data leakage.

In [96]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,19:] = sc.fit_transform(X_train[:,19:])
X_test[:,19:] = sc.fit_transform(X_test[:,19:])

In [97]:
X_train

array([[ 0.        ,  1.        ,  0.        , ..., -1.49101999,
         0.81254399,  0.76636516],
       [ 1.        ,  0.        ,  0.        , ...,  0.34560028,
        -0.74121494, -0.40159779],
       [ 1.        ,  0.        ,  0.        , ...,  0.80475535,
        -1.00017476, -0.48078172],
       ...,
       [ 1.        ,  0.        ,  0.        , ...,  0.34560028,
         0.81254399,  0.78616114],
       [ 0.        ,  1.        ,  0.        , ...,  1.26391042,
         0.29462434, -1.66854066],
       [ 0.        ,  1.        ,  1.        , ...,  1.37869918,
        -1.00017476,  0.23187364]])

In [98]:
X_test

array([[ 0.        ,  1.        ,  0.        , ...,  2.18008452,
        -0.47793949, -0.39718727],
       [ 1.        ,  0.        ,  0.        , ...,  0.23914189,
        -0.47793949, -0.21752274],
       [ 1.        ,  0.        ,  1.        , ..., -0.90258906,
         0.2813642 ,  0.58098631],
       ...,
       [ 0.        ,  1.        ,  0.        , ..., -0.44589668,
        -0.47793949,  1.040129  ],
       [ 1.        ,  0.        ,  0.        , ...,  0.35331499,
         0.53446544,  0.36139632],
       [ 0.        ,  1.        ,  0.        , ...,  0.58166118,
         0.02826297,  0.72072539]])